### ISSUE TITLE
Add background birthday song

### ISSUE THREAD

**Issue by akanksha-raghav** [akanksha-raghav/Birthday_wishes#1]
Add background birthday song after the gift click me component

**Comment by priyanshupardhi** [comment]
hey @akanksha-raghav do you have an audio file so that I can add a link

**Comment by akanksha-raghav** [comment]
> hey @akanksha-raghav do you have an audio file so that I can add a link

you can add any as per your wish😊

**Comment by priyanshupardhi** [comment]
@akanksha-raghav Ok I work in it
